apps/usuarios/urls.py
from django.conf.urls import url, include
from views import RegistroUsuario,UserHome, update_profile
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^registrar/', RegistroUsuario, name="registrar"),
    url(r'^$', login_required(UserHome), name="usuarios_home"),
    url(r'^misdatos/', login_required(update_profile), name="usuarios_datos"),
    ]

ra0admin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete, \
    logout_then_login
from django.contrib.auth.decorators import login_required
from apps.usuarios.views import UserHome, HomeRepositorio, HomeSenales

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('apps.usuarios.urls', namespace="usuarios")),
    url(r'^senales/', include('apps.senales.urls', namespace="senales")),
    url(r'^repositorio/', include('apps.repositorio.urls', namespace="repositorio")),
    url(r'^$', login_required(UserHome), name="land"),
    url(r'^accounts/login/', login, {'template_name': 'usuarios/index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name="logout"),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'usuarios/password_reset_fm.html',
         'email_template_name': 'usuarios/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'usuarios/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'usuarios/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'usuarios/password_reset_complete.html'},
        name='password_reset_complete'),
    url(r'^homesenales/', login_required(HomeSenales), name="senales_home"),
    url(r'^homerepositorio/', login_required(HomeRepositorio), name="repositorio_home"),
]

templates/base/base.html
<!DOCTYPE html>
<html lang=“es”>
    <head>
        {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
        <meta charset=“utf-8” />
        <title> {% block titulo %} RA-0 Admin {% endblock %}</title>
        {% block head %}
        {% endblock %}
    </head>
    <body>
    {% block header %}
    <h4> </h4>
    <h4> </h4>
    	<nav>
	 <ul class="fullnav">
         <li>
	        <a href="{% url 'usuarios:usuarios_home' %}">Home</a>
        </li>
         <li>
	        <div class="separador">|</div>
        </li>
         <li>
	        <a href="{% url 'senales_home' %}">Base de datos de señales</a>
        </li>
         <li>
	        <div class="separador">|</div>
        </li>
         <li>
	        <a href="{% url 'repositorio_home' %}">Repositorio de documentación</a>
        </li>
         <li>
	        <div class="separador">|</div>
        </li>
        <li>
	   		<a href="{% url 'usuarios:usuarios_datos' %}"> {{ request.user.username }} </a>
        </li>
         <li>
	        <div class="separador">|</div>
        </li>
         <li>
	   		<a href="{% url 'logout' %}">Salir</a>
        </li>
	 </ul>
	</nav>
    {% endblock %}

    {% block content %}
    <h5> </h5>
    <a href="{% url 'logout' %}">Salir</a>
    {% endblock %}

    {% block footer %}
    <h5> </h5>
    {% endblock %}
    </body>
</html>