apps/usuarios/urls.py
from django.conf.urls import url, include
from views import RegistroUsuario,UserHome, update_profile
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^registrar/', RegistroUsuario, name="registrar"),
    url(r'^$', login_required(UserHome), name="usuarios_home"),
    url(r'^misdatos/', login_required(update_profile), name="usuarios_datos"),
    ]

ra0admin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete, \
    logout_then_login
from django.contrib.auth.decorators import login_required
from apps.usuarios.views import UserHome, HomeRepositorio, HomeSenales

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('apps.usuarios.urls', namespace="usuarios")),
    url(r'^senales/', include('apps.senales.urls', namespace="senales")),
    url(r'^repositorio/', include('apps.repositorio.urls', namespace="repositorio")),
    url(r'^$', login_required(UserHome), name="land"),
    url(r'^accounts/login/', login, {'template_name': 'usuarios/index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name="logout"),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'usuarios/password_reset_fm.html',
         'email_template_name': 'usuarios/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'usuarios/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'usuarios/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'usuarios/password_reset_complete.html'},
        name='password_reset_complete'),
    url(r'^homesenales/', login_required(HomeSenales), name="senales_home"),
    url(r'^homerepositorio/', login_required(HomeRepositorio), name="repositorio_home"),
]

apps/usuarios/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Provincia(models.Model):
	name = models.CharField(max_length=400)

	def __str__(self):
		return (self.name)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organizacion = models.CharField(max_length=200, default='')
    email = models.EmailField(default='')
    nombre = models.CharField(max_length=200, default='')
    puesto = models.CharField(max_length=200, default='')
    provincia = models.ForeignKey(Provincia,default=1, null=True)
    localidad= models.CharField(max_length=200, null=True, blank=True, default='')
    direccion = models.CharField(max_length=500,null=True, blank=True, default='')
    telefono = models.CharField(max_length=50, default='')

    def __str__(self):
        return (self.user.username)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

apps/usuarios/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from models import Profile

class RegistroForm (UserCreationForm):

    class Meta:
        model = User
        fields = [
            'username',
        ]
        labels = {
            'username':'Nombre de usuario',
        }


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
        ]
        labels = {
            'username': 'Nombre de usuario',
        }


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('organizacion',
                  'nombre',
                  'email',
                  'puesto',
                  'provincia',
                  'localidad',
                  'direccion',
                  'telefono',
                  )
        labels = {
            'organizacion': 'Organizacion',
            'nombre':'Nombre completo',
            'email':'E-mail',
            'puesto':'Puesto',
            'provincia':'Provincia',
            'localidad':'Localidad',
            'direccion':'Direccion',
            'telefono':'Telefono',
        }

apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.core.urlresolvers import reverse_lazy
from forms import RegistroForm,ProfileForm, UserForm
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import redirect
from django.contrib import messages
from ..senales.models import Senal, Bornera
from ..repositorio.models import Publicacion


#class RegistroUsuario(CreateView):
#    model= User
#    template_name= "usuarios/registrar.html"
#    form_class = RegistroForm
#    second_form_class= ProfileForm
#    success_url = reverse_lazy('usuarios:usuarios_home')

def RegistroUsuario(request):
    if request.method == 'POST':
        user_form = RegistroForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            usuario=user_form.save()
            profile_form = ProfileForm(request.POST, instance=usuario.profile)
            profile_form.save()
            messages.success(request, 'Usuario creado exitosamente!')
            return redirect('usuarios:usuarios_home')
    else:
        user_form = RegistroForm()
        profile_form = ProfileForm()
    return render(request, 'usuarios/registrar.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

def UserHome(request):
    if request.method == 'POST':
        if (request.POST.get("tipobusqueda", "") == '1'):
            return BusquedaBornera(request=request)
        if (request.POST.get("tipobusqueda", "") == '2'):
            return BusquedaSenal(request=request)
        #print (request.POST.get("campobusqueda", ""))
        senales = Senal.objects.all()
        return render(request, 'home.html', {'senales': senales})

    senales = Senal.objects.all().order_by('nombre')
    publicaciones = Publicacion.objects.all().order_by('nombreDoc')
    return render(request,'home.html',{'senales':senales,'publicaciones':publicaciones})

@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            #messages.success(request, _('Your profile was successfully updated!'))
            return redirect('usuarios:usuarios_home')
        #else:
            #messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'usuarios/actualizar.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

def BusquedaSenal(request):
    print (request.POST.get("campobusqueda", ""))
    senales = Senal.objects.filter(nombre__iexact=request.POST.get("campobusqueda", ""))
    senales1 = Senal.objects.filter(codigo__iexact=request.POST.get("campobusqueda", ""))
    return render(request, 'busquedasenal.html', {'senales':senales,
                                                  'senales1':senales1})

def BusquedaBornera(request):
    print (request.POST.get("campobusqueda", ""))
    borneras = Bornera.objects.filter(name__iexact=request.POST.get("campobusqueda", ""))
    return render(request, 'busquedabornera.html', {'borneras':borneras})

def HomeSenales(request):
    if request.method == 'POST':
        if (request.POST.get("tipobusqueda", "") == '1'):
            return BusquedaBornera(request=request)
        if (request.POST.get("tipobusqueda", "") == '2'):
            return BusquedaSenal(request=request)
        #print (request.POST.get("campobusqueda", ""))
        senales = Senal.objects.all()
        return render(request, 'homesenales.html', {'senales': senales})

    senales = Senal.objects.all().order_by('nombre')
    publicaciones = Publicacion.objects.all().order_by('nombreDoc')
    return render(request,'homesenales.html',{'senales':senales,'publicaciones':publicaciones})

def HomeRepositorio(request):
    if request.method == 'POST':
        if (request.POST.get("tipobusqueda", "") == '1'):
            return BusquedaBornera(request=request)
        if (request.POST.get("tipobusqueda", "") == '2'):
            return BusquedaSenal(request=request)
        #print (request.POST.get("campobusqueda", ""))
        senales = Senal.objects.all()
        return render(request, 'homerepositorio.html', {'senales': senales})

    senales = Senal.objects.all().order_by('nombre')
    publicaciones = Publicacion.objects.all().order_by('nombreDoc')
    return render(request,'homerepositorio.html',{'senales':senales,'publicaciones':publicaciones})

templates/usuarios/actualizar.html
{% extends 'base/base.html' %}

{% block content %}
<div id="boxRegistro">
  <form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">Guardar cambios</button>
  </form>
</div>
{% endblock %}

templates/usuarios/index.html
{% extends 'base/base.html' %}
{% block header %}
{% endblock %}
{% block content %}

{% load static %}
<div id="RA0">
    <img src="{% static 'img/RA0.png' %}" style="margin: 30px auto;">
</div>

<div id="boxLogin">
<form method="post">


    {% csrf_token %}
    <table>
        <tr>
            <td><label for="username">Nombre de usuario:</label></td>
            <td><input class="form-control" type="text" name="username"></td>
        </tr>
        <tr>
            <td><label for="password">Contraseña:</label></td>
            <td><input class="form-control" type="password" name="password"></td>
        </tr>
        <tr>
            <table><tr>
                <td><a href="{% url 'password_reset' %}">Olvidé mi contraseña</a></td>
                <td><a href="{% url 'usuarios:registrar' %}">Registrarse</a></td>
                <td><button type="submit">Ingresar</button></td>
            </tr></table>
        </tr>
    </table>
</form>
    {% if form.non_field_errors %}
        {{ form.non_field_errors }}
    {% endif %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

</div>

{% endblock %}

templates/usuarios/password_reset_complete.html
{% extends 'base/base.html' %}
{% block header %}
{% endblock %}
{% block content %}
<div id="boxLogin">
<h4>Su contraseña se reestableció correctamente</h4>


<p><a href="{% url 'login' %}"> Iniciar sesión</a></p>
</div>

{% endblock %}

templates/usuarios/password_reset_confirm.html
{% extends 'base/base.html' %}
{% block header %}
{% endblock %}
{% block content %}

{% if validlink %}
<div id="boxLogin">
<h1>Nueva Contraseña</h1>
<form method="post">
    {% csrf_token %}
    {{ form.new_password1.errors }}
        <label for="password1">Nueva Contraseña:</label>
    {{ form.new_password1 }}

    {{ form.new_password2.errors }}
        <label for="password2">Confirme Contraseña:</label>
    {{ form.new_password2 }}

    <button type="submit">Cambiar mi contraseña</button>
</form>
{% else %}

<h1>Enlace inválido: Este enlace ya ha sido utilizado</h1>

{% endif %}
</div>
{% endblock %}

templates/usuarios/password_reset_done.html
{% extends 'base/base.html' %}
{% block header %}
{% endblock %}
{% block content %}
<div id="boxLogin">
<h4>Te hemos enviado un correo con un enlace para reetablecer tu contraseña</h4>
</div>
{% endblock %}

templates/usuarios/password_reset_email.html
Solicitaste reestablecer tu contraseña
Click en el siguiente link para crear una nueva contraseña
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
Tu nombre de usuario es: {{ user.get_username }}

templates/usuarios/password_reset_fm.html
{% extends 'base/base.html' %}
{% block header %}
{% endblock %}
{% block content %}
<div id="boxLogin">
<p>Recuperar contraseña</p>
<form method="post">
    {% csrf_token %}
    <label for="id_email">E-mail:</label>{{ form.email }}
    <button type="submit">Enviar</button>
</form>
</div>
{% endblock %}

templates/usuarios/registrar.html
{% extends 'base/base.html' %}
{% block header %}
{% endblock %}
{% block content %}
<div id="boxRegistro">
    <form method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <button type="submit">Guardar</button>
    </form>
</div>
{% endblock %}