apps/repositorio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from views import Nuevo, ActualizaPublicacion, EliminaRevision, NuevaRevision, FinalizarElaboracion, Revisar, Aprobar

urlpatterns = [
    url(r'^nuevo/', login_required(Nuevo), name="nuevo"),
    url(r'^actualizapublicacion/(?P<id>\d+)/$', login_required(ActualizaPublicacion), name='actualizapublicacion'),
    url(r'^eliminarevision/(?P<idp>\d+)/(?P<idr>\d+)/$', login_required(EliminaRevision), name='eliminarevision'),
    url(r'^nuevarevision/(?P<idp>\d+)/$', login_required(NuevaRevision), name='nuevarevision'),
    url(r'^finalizarelaboracion/(?P<idp>\d+)/$', login_required(FinalizarElaboracion), name='finalizarelaboracion'),
    url(r'^revisar/(?P<idp>\d+)/$', login_required(Revisar), name='revisar'),
    url(r'^aprobar/(?P<idp>\d+)/$', login_required(Aprobar), name='aprobar'),
]

apps/senales/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from views import Nueva, NuevaBornera, ActualizaSenal, EliminaConexion, NuevaConexion, ConexionesBornera, NuevoChasis

urlpatterns = [
    url(r'^nueva/', login_required(Nueva), name="nueva"),
    url(r'^nuevabornera/', login_required(NuevaBornera), name="nuevabornera"),
    url(r'^nuevochasis/', login_required(NuevoChasis), name="nuevochasis"),
    url(r'^actualizasenal/(?P<id>\d+)/$', login_required(ActualizaSenal), name='actualizasenal'),
    url(r'^eliminaconexion/(?P<ids>\d+)/(?P<idc>\d+)/$', login_required(EliminaConexion), name='eliminaconexion'),
    url(r'^nuevaconexion/(?P<id>\d+)/$', login_required(NuevaConexion), name="nuevaconexion"),
    url(r'^conexionesbornera/(?P<id>\d+)/$', login_required(ConexionesBornera), name="conexionesbornera"),
]

ra0admin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete, \
    logout_then_login
from django.contrib.auth.decorators import login_required
from apps.usuarios.views import UserHome, HomeRepositorio, HomeSenales

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('apps.usuarios.urls', namespace="usuarios")),
    url(r'^senales/', include('apps.senales.urls', namespace="senales")),
    url(r'^repositorio/', include('apps.repositorio.urls', namespace="repositorio")),
    url(r'^$', login_required(UserHome), name="land"),
    url(r'^accounts/login/', login, {'template_name': 'usuarios/index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name="logout"),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'usuarios/password_reset_fm.html',
         'email_template_name': 'usuarios/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'usuarios/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'usuarios/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'usuarios/password_reset_complete.html'},
        name='password_reset_complete'),
    url(r'^homesenales/', login_required(HomeSenales), name="senales_home"),
    url(r'^homerepositorio/', login_required(HomeRepositorio), name="repositorio_home"),
]

templates/actualizasenal.html
{% extends 'base/base.html' %}

{% block content %}
<div id="boxSenal">
<form method="post">
    {% csrf_token %}
    {{ senalform.as_p }}
    <button type="submit">Guardar</button>
</form>
<br>
<a href="{% url 'senales:nuevaconexion' senal.id %}" class="boton">Nueva conexión</a>
<h3>Conexiones:</h3>
<div class="datagrid">
<table>
	<thead>
	<tr>
		<th>Bornera</th>
        <th>Pin</th>
        <th>Tipo</th>
        <th>Orden</th>
        <th>Comentarios</th>
        <th>Acción</th>
	</tr>
	</thead>
    <tbody>
	{% for con in conexiones %}
	<tr>
		<td>{{ con.bornera.name }}</td>
        <td>{{ con.pin }}</td>
        <td>{{ con.tipoConexion.name }}</td>
        <td>{{ con.orden }}</td>
        <td>{{ con.descripcion }}</td>
        <td><a href="{% url 'senales:eliminaconexion' con.senal.id con.id %}">Borrar</a></td>
	</tr>
	{% endfor %}
    </tbody>
</table>
</div>

{% endblock %}

templates/busquedabornera.html
{% extends 'base/base.html' %}

{% block content %}
<div id="boxSenal">
<h3>Resultado de su búsqueda:</h3>
<div class="datagrid">
	<table>
	<thead>
	<tr>
		<th>Bornera</th>
        <th>Descripción</th>
	</tr>
	</thead>
	<tbody>
	{% for bor in borneras %}
	<tr>
		<td><a href="{% url 'senales:conexionesbornera' bor.id %}">{{ bor.name }}</a></td>
        <td>{{ bor.description }}</td>
	</tr>
	{% endfor %}
	</tbody>
</table>
</div>
</div>

{% endblock %}

templates/busquedasenal.html
{% extends 'base/base.html' %}

{% block content %}
<div id="boxSenal">

<h3>Resultado de su búsqueda:</h3>
<div class="datagrid">
<table>
	<thead>
	<tr>
		<th>Señal</th>
        <th>Código</th>
        <th>Tipo</th>
        <th>Rango</th>
	</tr>
	</thead>
	<tbody>
	{% for sen in senales %}
	<tr>
		<td><a href="{% url 'senales:actualizasenal' sen.id %}">{{ sen.nombre }}</a></td>
        <td>{{ sen.codigo }}</td>
        <td>{{ sen.tipoSenal.name }}</td>
        <td>{{ sen.rango }}</td>
	</tr>
	{% endfor %}
    	{% for sen in senales1 %}
	<tr>
		<td><a href="{% url 'senales:actualizasenal' sen.id %}">{{ sen.nombre }}</a></td>
        <td>{{ sen.codigo }}</td>
        <td>{{ sen.tipoSenal.name }}</td>
        <td>{{ sen.rango }}</td>
	</tr>
	{% endfor %}
	</tbody>
</table>
</div>
</div>

{% endblock %}

templates/conexionesbornera.html
{% extends 'base/base.html' %}

{% block content %}
<div id="boxSenal">
<h3>Conexiones de la Bornera {{ bornera.name }} </h3>
<div class="datagrid">
<table>
	<thead>
	<tr>
		<th>Nombre de señal</th>
        <th>Código de señal</th>
        <th>Tipo de conexión</th>
        <th>Pin</th>
		<th>Descripción</th>
	</tr>
	</thead>
	<tbody>
	{% for con in conexiones %}
	<tr>
		<td>{{ con.senal.nombre }}</td>
        <td>{{ con.senal.codigo }}</td>
        <td>{{ con.tipoConexion.name}}</td>
        <td>{{ con.pin }}</td>
		<td>{{ con.descripcion}}</td>
	</tr>
	{% endfor %}
	</tbody>
</table>
</div>
</div>

{% endblock %}

templates/home.html
{% extends 'base/base.html' %}

{% block content %}
{% load static %}
	<div id="RA0Home">
		<img src="{% static 'img/RA0.png' %}" style="margin: 30px auto;">
	</div>
	<div id="boxHome2">
		El Reactor Nuclear RA-0 es un reactor de los denominados de potencia cero. Esto significa que trabaja normalmente a potencias muy bajas (del orden de 1 watt). Esta característica hace que no necesite sistema de refrigeración, pues el calor producido en el núcleo es muy poco. El núcleo del reactor tiene una geometría de corona circular formada por dos tanques concéntricos y separables de aluminio anodizado. El tanque interior es postizo y desmontable para permitir eventuales trabajos laterales que requieran configuraciones cilíndricas o no anulares. Los elementos combustibles son de una mezcla en peso de 70% de óxido de uranio enriquecido al 20,09 % en uranio 235 (U235), 15% de brea aglutinante y 15% de grafito. Dicha mezcla es extrudada, desgasada y envainada en aluminio anodizado. Limitando la zona activa del núcleo, existen dos volúmenes de reflector de grafito de pureza nuclear, que tiene perforaciones en las cuales se alojan los instrumentos de medición. Como moderador, se usa agua liviana desmineralizada, la cual es almacenada en un tanque de reserva ubicado a nivel del piso. Una bomba centrífuga impulsa el agua a través de un calefactor de inmersión hacia el tanque del reactor. El llenado sólo es posible cuando una válvula de seguridad está en posición cerrada. La cañería de impulsión tiene una estrangulación de modo que la velocidad de llenado está limitada a valores compatibles con los requerimientos de seguridad. Esto es así pues el llenado implica adición de reactividad. La bomba del moderador posee un accionamiento manual y uno mecánico (temporizado) desde la consola de control. La válvula de seguridad conectada en la línea de descarga que va desde el tanque del núcleo al tanque de reserva, se abre mediante la acción de una serie de resortes tensionados que garantizan la falla de la misma hacia la condición más segura. El cierre se efectúa mediante electroimanes cuando se dan las condiciones lógicas para la inundación del núcleo.
	</div>

{% endblock %}

templates/homerepositorio.html
{% extends 'base/base.html' %}

{% block content %}


			<div id="boxHome1">
				<h2>Seguimiento de documentación</h2>
			<a href="{% url 'repositorio:nuevo' %}" class="boton">Nuevo documento</a>
			<h3>Publicaciones:</h3>
                <div class="datagrid">
                <table>
                    <thead>
                    <tr>
                        <th>Documento</th>
                        <th>Codificación</th>
                        <th>Estado</th>
                        <th>Ubicacion</th>
                        <th>Última actualizacion</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for pub in publicaciones %}
                    <tr>
                        <td><a href="{% url 'repositorio:actualizapublicacion' pub.id %}">{{ pub.nombreDoc }}</a></td>
                        <td>{{ pub.codificacion }}</a></td>
                        <td>{{ pub.estado.nombre }}</a></td>
                        <td>{{ pub.ubicacion }}</a></td>
                        <td>{{ pub.fechaActualizacion }}</a></td>
                    </tr>
                    {% endfor %}
                    <tbody>
                </table>
                </div>
			</div>


{% endblock %}

templates/homesenales.html
{% extends 'base/base.html' %}

{% block content %}

		<div id="boxHome">
			<h2>Base de datos de Señales</h2>

			<a href="{% url 'senales:nueva' %}" class="boton">Nueva señal</a>
			<a href="{% url 'senales:nuevabornera' %}" class="boton">Nueva bornera</a>
			<a href="{% url 'senales:nuevochasis' %}" class="boton">Nuevo chasis</a>
			<br><br>
			<h3>Búsqueda:</h3>

			<form method="post" id="busqueda">
				{% csrf_token %}
				<input type="radio" name="tipobusqueda" value=1  class="busquedaradio" checked="true"> Por Bornera<br>
				<input type="radio" name="tipobusqueda" value=2  class="busquedaradio" > Por Señal<br>
				<input type="text" name="campobusqueda" class="busquedatxt">
				<button type="submit">Buscar</button>

			</form>
			<br>
            <h2>Listado de señales</h2>
			<div class="datagrid">
			<table>
				<thead>
				<tr>
					<th>Señal</th>
					<th>Código</th>
					<th>Tipo</th>
					<th>Rango</th>
				</tr>
				</thead>
				<tbody>
				{% for sen in senales %}
				<tr>
					<td><a href="{% url 'senales:actualizasenal' sen.id %}">{{ sen.nombre }}</a></td>
					<td>{{ sen.codigo }}</td>
					<td>{{ sen.tipoSenal.name }}</td>
					<td>{{ sen.rango }}</td>
				</tr>
				{% endfor %}
				</tbody>
			</table>
			</div>
		</div>


{% endblock %}

templates/nuevabornera.html
{% extends 'base/base.html' %}

{% block content %}
<div id="boxHome">
<form method="post">
    {% csrf_token %}
    {{ borneraForm.as_p }}
    <button type="submit">Guardar</button>
</form>
</div>
{% endblock %}

templates/nuevaconexion.html
{% extends 'base/base.html' %}

{% block content %}
<div id="boxHome">
<form method="post">
    {% csrf_token %}
    {{ conexionForm.as_p }}
    <button type="submit">Guardar</button>
</form>
</div>
{% endblock %}

templates/nuevapublicacion.html
{% extends 'base/base.html' %}

{% block content %}
<div id="boxPublicacion">
<form method="post">
    {% csrf_token %}
    {{ publicacionForm.as_p }}
    <button type="submit">Guardar</button>
</form>
</div>
{% endblock %}

templates/nuevarevision.html
{% extends 'base/base.html' %}

{% block content %}
<div id="boxHome">
<form method="post">
    {% csrf_token %}
    {{ revisionForm.as_p }}
    <button type="submit">Guardar</button>
</form>
</div>

{% endblock %}

templates/nuevasenal.html
{% extends 'base/base.html' %}

{% block content %}
<div id="boxHome">
<form method="post">
    {% csrf_token %}
    {{ senalform.as_p }}
    <button type="submit">Guardar</button>
</form>
</div>
{% endblock %}

templates/nuevochasis.html
{% extends 'base/base.html' %}

{% block content %}
<div id="boxHome">
<form method="post">
    {% csrf_token %}
    {{ chasisForm.as_p }}
    <button type="submit">Guardar</button>
</form>
</div>
{% endblock %}

templates/revisar.html
{% extends 'base/base.html' %}

{% block content %}
<div id="boxHome">
<form method="post">
    {% csrf_token %}
    {{ revisionForm.as_p }}
    <button type="submit">Guardar</button>
</form>
</div>
{% endblock %}